{
  "uid" : "575601722c412f56",
  "name" : "test_2",
  "fullName" : "Test.test_search.Test_Base#test_2",
  "historyId" : "3076e89e749c67a48d0075dc4be40f5f",
  "time" : {
    "start" : 1572390568332,
    "stop" : 1572390568332,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。",
  "statusTrace" : "self = <test_search.Test_Base object at 0x0442A990>\n\n    def setup(self):\n>       self.driver = init_driver()\n\nTest\\test_search.py:10: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nBasic\\Init_Driver.py:20: in init_driver\n    driver = webdriver.Remote(\"http://127.0.0.1:4723/wd/hub\",desired_caps)\nc:\\users\\admin900625\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\appium_python_client-0.25-py3.6.egg\\appium\\webdriver\\webdriver.py:36: in __init__\n    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)\n..\\..\\..\\..\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:91: in __init__\n    self.start_session(desired_capabilities, browser_profile)\n..\\..\\..\\..\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:173: in start_session\n    'desiredCapabilities': desired_capabilities,\n..\\..\\..\\..\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:231: in execute\n    response = self.command_executor.execute(driver_command, params)\n..\\..\\..\\..\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py:395: in execute\n    return self._request(command_info[0], url, body=data)\n..\\..\\..\\..\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py:463: in _request\n    resp = opener.open(request, timeout=self._timeout)\n..\\..\\..\\..\\appdata\\local\\programs\\python\\python36-32\\lib\\urllib\\request.py:526: in open\n    response = self._open(req, data)\n..\\..\\..\\..\\appdata\\local\\programs\\python\\python36-32\\lib\\urllib\\request.py:544: in _open\n    '_open', req)\n..\\..\\..\\..\\appdata\\local\\programs\\python\\python36-32\\lib\\urllib\\request.py:504: in _call_chain\n    result = func(*args)\n..\\..\\..\\..\\appdata\\local\\programs\\python\\python36-32\\lib\\urllib\\request.py:1346: in http_open\n    return self.do_open(http.client.HTTPConnection, req)\n..\\..\\..\\..\\appdata\\local\\programs\\python\\python36-32\\lib\\urllib\\request.py:1321: in do_open\n    r = h.getresponse()\n..\\..\\..\\..\\appdata\\local\\programs\\python\\python36-32\\lib\\http\\client.py:1331: in getresponse\n    response.begin()\n..\\..\\..\\..\\appdata\\local\\programs\\python\\python36-32\\lib\\http\\client.py:297: in begin\n    version, status, reason = self._read_status()\n..\\..\\..\\..\\appdata\\local\\programs\\python\\python36-32\\lib\\http\\client.py:258: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <socket.SocketIO object at 0x043FF8F0>, b = <memory at 0x04383308>\n\n    def readinto(self, b):\n        \"\"\"Read up to len(b) bytes into the writable buffer *b* and return\n        the number of bytes read.  If the socket is non-blocking and no bytes\n        are available, None is returned.\n    \n        If *b* is non-empty, a 0 return value indicates that the connection\n        was shutdown at the other end.\n        \"\"\"\n        self._checkClosed()\n        self._checkReadable()\n        if self._timeout_occurred:\n            raise OSError(\"cannot read from timed out object\")\n        while True:\n            try:\n>               return self._sock.recv_into(b)\nE               ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。\n\n..\\..\\..\\..\\appdata\\local\\programs\\python\\python36-32\\lib\\socket.py:586: ConnectionResetError",
  "flaky" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "Test"
  }, {
    "name" : "suite",
    "value" : "test_search"
  }, {
    "name" : "subSuite",
    "value" : "Test_Base"
  }, {
    "name" : "host",
    "value" : "DESKTOP-E3BR8K0"
  }, {
    "name" : "thread",
    "value" : "23992-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "Test.test_search"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "575601722c412f56.json",
  "parameterValues" : [ ]
}